name: Promote Staging to Production

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirm promotion of current staging to production'
        required: true
        type: boolean
        default: false
      release_message:
        description: 'Release message for the deployment'
        required: true
        type: string
        default: 'Promoting staging to production'
      bump_type:
        description: 'Version bump type (major, minor, patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

jobs:
  create-release:
    name: Create Release
    if: github.event.inputs.confirmation == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.bump_type }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: 'Release ${{ steps.tag_version.outputs.new_tag }}'
          target_commitish: ${{ github.sha }}
          body: |
            <div id="releaseData">
            <div><strong>type:</strong> <span class="type">${{ github.event.inputs.bump_type }}</span></div>
            <div><strong>description:</strong> <span class="description">${{ github.event.inputs.release_message }}</span></div>
            <div><strong>commit id:</strong> <span class="commitId">${{ github.sha }}</span></div>
            </div>
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
