name: Promote Staging to Production

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirm promotion of current staging to production'
        required: true
        type: boolean
        default: false
      release_message:
        description: 'Release message for the deployment'
        required: true
        type: string
        default: 'Promoting staging to production'

jobs:
  create-release:
    name: Create Release
    if: github.event.inputs.confirmation == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{ github.run_number }}'
          release_name: 'Release v${{ github.run_number }}'
          body: ${{ github.event.inputs.release_message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
