# name: jira-description-action
# on:
#   pull_request:
#     branches:
#       - main
#     types: [opened]
# jobs:
#   add-jira-description:
#     if: contains(github.event.pull_request.labels.*name, 'sprint')
#     runs-on: ubuntu-latest
#     steps:
#       - uses: cakeinpanic/jira-description-action@v0.3.3
#         name: jira-description-action
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           jira-token: ${{ secrets.JIRA_TOKEN }}
#           jira-base-url: https://your-domain.atlassian.net
#           skip-branches: '^(production-release|main|master|release\/v\d+)$' #optional 
#           custom-issue-number-regexp: '^\d+' #optional
#           jira-project-key: 'PRJ' #optional    
