name: Update Sprint PR description
on:
  pull_request:
    types: [opened]
    branches:
      - feature/sprint/*
permissions:
  contents: write
  pull-requests: write
jobs:
  add_jira_description:
    runs-on: ubuntu-latest
    steps:
      - uses: as-ideas/jira-description-action@master
        name: Add JIRA details to PR description
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          custom-issue-number-regexp: '.*_(\d+)$' # Gets sprint ID from branch
          use: 'branch'